apiVersion: v1
kind: Pod
metadata:
  name: mysql
  # NOTE: Added the following 2 lines:
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Hs0%EUovc$R9pEPV
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: mysql-initdb
      configMap:
        name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE auth;
    USE auth;
    CREATE TABLE user (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL);
    INSERT INTO user (email, password) VALUES ('gg@email.com', 'Yn23*re8*ikMMT2@');
